// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsvafjkrksxmpvrnfcyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdmFmamtya3N4bXB2cm5mY3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODQ2NjQsImV4cCI6MjA2NzE2MDY2NH0.Lbk7_TNo8GqQNKxhiN21V5PDrsWxDxOkPKiOeP9UJR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});